### ISSUE TITLE
cclient: get_transactions_to_approve call error when reference is null

### ISSUE THREAD

**Issue by wusyong** [iotaledger/entangled#668]
Calling get_transactions_to_approve without setting reference would cause error:
``` bash
cclient_core_api:   INFO: [iota_client_core_init:17] enable logger cclient_core_api.
types:   INFO: [logger_init_types:18] enable logger types.
json_serializer:   INFO: [logger_init_json_serializer:19] enable logger json_serializer.

[test_tx_to_approve]
cclient_core_api:   INFO: [iota_client_get_transactions_to_approve:393]
json_serializer:   INFO: [json_get_transactions_to_approve_serialize_request:1103]
[1]    42718 segmentation fault  bazel run :app
```

The reason I think is that `flex_trits_are_null()` in [json_serializer.c](https://github.com/iotaledger/entangled/blob/develop/cclient/serialization/json/json_serializer.c#L1116) is not same as constructor of `get_transactions_to_approve_req_new`(which set reference to`NULL`). The "null flex trits" of `flex_trits_are_null` means each trit is `FLEX_TRIT_NULL_VALUE` instead.

We could specific the reference like this as for now:
```
flex_trit_t reference[FLEX_TRIT_SIZE_243];
memset(reference, FLEX_TRIT_NULL_VALUE, FLEX_TRIT_SIZE_243);
get_transactions_to_approve_req_set_reference(req, reference);
```
However, maybe we should either initialize the reference or change how serializer checks, since reference is optional and doesn't need to specify by default imo.

**Comment by oopsmonk** [comment]
assume you are using https://github.com/oopsmonk/iota_cclient_example
it's based on 08f6a1be4deb4b323f23a53aac94de8432d9a46b and out-of-date, but I'll update the example code later. 
this issue has been fixed recently.

**Comment by wusyong** [comment]
I had updated commit version, but the issue is still same. Above is the result using [`64633f5`](https://github.com/iotaledger/entangled/commit/64633f5efa33a2be7fa1eca26a405b34be268794)

**Comment by oopsmonk** [comment]
got it. the problem is the initialization had been changed in the request but the json serialization didn't do the corresponding change. thanks for your report.
